// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconBxsBuildingHouse: typeof import('~icons/bxs/building-house')['default']
    IconBxsCaretRightCircle: typeof import('~icons/bxs/caret-right-circle')['default']
    IconBxsPauseCircle: typeof import('~icons/bxs/pause-circle')['default']
    IconBxsSearchAlt: typeof import('~icons/bxs/search-alt')['default']
    IconBxsSearchAlt2: typeof import('~icons/bxs/search-alt2')['default']
    IconBxsSkipNextCircle: typeof import('~icons/bxs/skip-next-circle')['default']
    IconBxsSkipPreviousCircle: typeof import('~icons/bxs/skip-previous-circle')['default']
    IconEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IconIconParkSolidFormatBrush: typeof import('~icons/icon-park-solid/format-brush')['default']
    IconIconParkTwotoneCategoryManagement: typeof import('~icons/icon-park-twotone/category-management')['default']
    IconIconParkTwotoneCoconutTree: typeof import('~icons/icon-park-twotone/coconut-tree')['default']
    IconIconParkTwotoneDolphin: typeof import('~icons/icon-park-twotone/dolphin')['default']
    IconIconParkTwotoneFormatBrush: typeof import('~icons/icon-park-twotone/format-brush')['default']
    IconIconParkTwotoneHome: typeof import('~icons/icon-park-twotone/home')['default']
    IconIconParkTwotoneKoalaBear: typeof import('~icons/icon-park-twotone/koala-bear')['default']
    IconIcTwotonePauseCircleFilled: typeof import('~icons/ic/twotone-pause-circle-filled')['default']
    IconIcTwotonePlayCircleFilled: typeof import('~icons/ic/twotone-play-circle-filled')['default']
    IconIcTwotoneSkipNext: typeof import('~icons/ic/twotone-skip-next')['default']
    IconIcTwotoneSkipPrevious: typeof import('~icons/ic/twotone-skip-previous')['default']
    IconLineMdSearch: typeof import('~icons/line-md/search')['default']
    IconPepiconsPause: typeof import('~icons/pepicons/pause')['default']
    IconPepiconsPausePrint: typeof import('~icons/pepicons/pause-print')['default']
    Lyrics: typeof import('./src/components/Lyrics/index.vue')['default']
    LyricsBar: typeof import('./src/components/Lyrics/LyricsBar.vue')['default']
    LyricsPlayBar: typeof import('./src/components/Lyrics/LyricsPlayBar.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PlayBar: typeof import('./src/components/Player/PlayBar.vue')['default']
    Player: typeof import('./src/components/Player/index.vue')['default']
    PlayerLyrics: typeof import('./src/components/Player/Lyrics/PlayerLyrics.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
    TouchStick: typeof import('./src/components/TouchStick.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSlider: typeof import('vant/es')['Slider']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTimePicker: typeof import('vant/es')['TimePicker']
  }
}

export {}
