// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconBxsBuildingHouse: typeof import('~icons/bxs/building-house')['default']
    IconBxsCaretRightCircle: typeof import('~icons/bxs/caret-right-circle')['default']
    IconBxsPauseCircle: typeof import('~icons/bxs/pause-circle')['default']
    IconBxsSkipNextCircle: typeof import('~icons/bxs/skip-next-circle')['default']
    IconBxsSkipPreviousCircle: typeof import('~icons/bxs/skip-previous-circle')['default']
    IconEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    PlayBar: typeof import('./src/components/PlayBar.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
    TouchStick: typeof import('./src/components/TouchStick.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanRate: typeof import('vant/es')['Rate']
    VanSlider: typeof import('vant/es')['Slider']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTimePicker: typeof import('vant/es')['TimePicker']
  }
}

export {}
